col = { 
       "name" : "Nom et Prénoms",
       "im" : "IM",
       "matricule" : "Matricule",
       "grade" : "Grade",
       "height" : "Taille",
       "genre" : "Sexe",
       "blood" : "Groupe Sanguin",
       "birthday" : "Date de naissance",
       "birthplace" : "Lieu de naissance",
       "name_father" : "Nom du père",
       "job_father" : "Profession",
       "name_mother" : "Nom de la mère",
       "job_mother" : "Profession",
       "cin" : "N° CIN",
       "date_cin" : "Date de délivrance CIN",
       "place_cin" : "Lieu de délivrance CIN",
       "region_origin" : "Region d'orgine",
       "ethnie" : "Ethnie",
       "address" : "Adresse",
       "phone" : "Téléphone",
       "email" : "Email",
       "phone2" : "Téléphone en cas d'urgence",
}